version: '3'

volumes:
  log-data:
  esdata:

networks:
  efk-stack:

services:
  fluentd:
    image: wework/fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - efk-stack
    expose:
      - "24224"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    networks:
      - efk-stack
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    networks:
      - efk-stack
    ports:
      - "5601:5601"

